name: Samsung Firmware Update Checker

on:
  workflow_dispatch:
    inputs:
      model:
        description: 'Device Model (e.g., SM-A155F)'
        required: true
        default: 'SM-A155F'
      region:
        description: 'Region Code / CSC (e.g., EUX, XSG, DBT)'
        required: true
        default: 'EUX'
  
  schedule:
    - cron: '0 0 * * *'

jobs:
  check-for-update:
    runs-on: ubuntu-latest

    steps:
      - name: Setup .NET 8.0 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Clone SamsungFumoClient repository
        uses: actions/checkout@v4
        with:
          repository: 'timschneeb/SamsungFumoClient'
          path: 'SamsungFumoClient'

      - name: Run Firmware Check
        working-directory: ./SamsungFumoClient
        run: |
          echo "========================================================"
          echo "Checking for firmware update..."
          echo "Model: ${{ github.event.inputs.model || 'SM-A155F' }}"
          echo "Region: ${{ github.event.inputs.region || 'EUX' }}"
          echo "========================================================"
          
          OPENSSL_CONF=openssl.custom dotnet run --project DemoClient -- --model ${{ github.event.inputs.model || 'SM-A155F' }} --region ${{ github.event.inputs.region || 'EUX' }}

