name: Samsung Firmware Checker (DEBUGGING)

on:
  workflow_dispatch:
    inputs:
      model:
        description: 'Device Model'
        required: true
        default: 'SM-A155F'
      region:
        description: 'Region Code / CSC'
        required: true
        default: 'EUX'

jobs:
  debug-curl:
    runs-on: ubuntu-latest

    steps:
      - name: Send Basic Curl Request
        run: |
          echo "Sending the most basic request possible..."
          
          # استخدام علامات الاقتباس المفردة حول البيانات والترويسات لتجنب أي تفسير من bash
          curl --verbose \
               -H 'Content-Type: application/xml;charset=UTF-8' \
               -H 'Authorization: FUS nonce="", signature="", t="", type="", version=""' \
               -d '<REQUEST><FUS><SERVICE><NAME>CHECK_FIRMWARE</NAME><VERSION>2.0</VERSION></SERVICE><CLIENT><TYPE>Smart Switch</TYPE><VERSION>4.3.24033_1</VERSION></CLIENT><DEVICE><MODEL_NAME>${{ github.event.inputs.model }}</MODEL_NAME><CSC>${{ github.event.inputs.region }}</CSC></DEVICE></FUS></REQUEST>' \
               "https://neofussvr.ssl.samsung.com/NF_Download.do"
               
          echo "Curl command finished."
