name: Deep Network Diagnostics

on:
  workflow_dispatch:

jobs:
  network-test:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Check DNS Resolution
        run: |
          echo "### Attempting to resolve neofussvr.samsung.com ###"
          nslookup neofussvr.samsung.com
          echo "-------------------------------------------------"
          
          echo "### Attempting to resolve fus.samsung.com ###"
          nslookup fus.samsung.com
          echo "-------------------------------------------------"

      - name: 2. Check Network Path (Traceroute)
        run: |
          echo "### Tracing route to neofussvr.samsung.com ###"
          # We need to install traceroute first
          sudo apt-get update && sudo apt-get install -y traceroute
          traceroute neofussvr.samsung.com
          echo "-------------------------------------------------"

      - name: 3. Test Basic Curl Connection (No Data)
        run: |
          echo "### Attempting a simple curl request with extreme verbosity ###"
          # This command only tries to connect and prints everything.
          curl --verbose --head "https://neofussvr.samsung.com/NF_Download.do"
          echo "-------------------------------------------------"
          
          echo "### Testing with the previous incorrect host to confirm the error ###"
          # This should fail with exit code 6, to prove our theory.
          curl --verbose "https://neofussvr.ssl.samsung.com" || echo "This failed as expected."
